title: Giovanni Marchetti
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

links:
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: Software/Data
    url: /softwaredata/


theme: jekyll-theme-minimal