
title: Giovanni M. Marchetti

description: Professor in the Department of Statistics, Computer Science, Applications(http://www.disia.unifi.it) 
[University of Florence](http://www.unifi.it)

- Office:  viale Morgagni, 59, 51134 Florence, Italy 
- Email: giovanni.marchetti at disia unifi.it  
- Phone: +39 055 275 1516

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

  theme: jekyll-theme-minimal